import type { ExperienceNavIconId } from './experience.types';

export interface NavCatalogEntry {
  href: string;
  label: string;
  description: string;
  iconId: ExperienceNavIconId;
  groupId: string;
  sidebarTier: 'core' | 'extended';
  permission?: string;
  planFeature?: string;
  restaurantFeature?: string;
  restaurantFeatures?: string[];
  requiresMainCash?: boolean;
  moduleId?: string;
}

export const NAV_GROUP_META: Record<
  string,
  { label: string; shortLabel: string; iconId: ExperienceNavIconId }
> = {
  operacion: {
    label: 'En el local',
    shortLabel: 'Local',
    iconId: 'chef-hat',
  },
  negocio: {
    label: 'Tu negocio',
    shortLabel: 'Negocio',
    iconId: 'trending-up',
  },
  ventas: {
    label: 'Carta y clientes',
    shortLabel: 'Carta',
    iconId: 'globe',
  },
  config: {
    label: 'Ajustes',
    shortLabel: 'Ajustes',
    iconId: 'wrench',
  },
};

export const NAV_CATALOG: NavCatalogEntry[] = [
  {
    href: '/admin',
    label: 'Hoy',
    description: '¿Qué necesita mi atención?',
    iconId: 'layout-dashboard',
    groupId: 'dashboard',
    sidebarTier: 'core',
    permission: 'dashboard',
  },
  {
    href: '/admin/turno',
    label: 'Turno en vivo',
    description: 'Pedidos, salón, cocina y apertura/cierre del turno',
    iconId: 'calendar-clock',
    groupId: 'operacion',
    sidebarTier: 'core',
    restaurantFeature: 'orders',
    permission: 'dashboard',
    moduleId: 'orders',
  },
  {
    href: '/admin/turno?lens=caja',
    label: 'Cola de pedidos',
    description: '¿Qué pedidos requieren acción?',
    iconId: 'clipboard-list',
    groupId: 'operacion',
    sidebarTier: 'extended',
    restaurantFeature: 'orders',
    permission: 'orders',
    moduleId: 'orders',
  },
  {
    href: '/admin/turno?lens=encargado',
    label: 'Apertura y cierre',
    description: 'Listas de apertura, cierre y traspaso de turno',
    iconId: 'calendar-clock',
    groupId: 'operacion',
    sidebarTier: 'extended',
    restaurantFeatures: ['orders', 'menu'],
    permission: 'salon',
    moduleId: 'orders',
  },
  {
    href: '/admin/salon',
    label: 'Salón',
    description: '¿Cómo está el salón ahora?',
    iconId: 'concierge-bell',
    groupId: 'operacion',
    sidebarTier: 'core',
    restaurantFeature: 'salon',
    permission: 'salon',
    moduleId: 'salon',
  },
  {
    href: '/kitchen',
    label: 'Cocina',
    description: '¿Qué preparo ahora?',
    iconId: 'chef-hat',
    groupId: 'operacion',
    sidebarTier: 'core',
    planFeature: 'kitchen_display',
    restaurantFeature: 'orders',
    permission: 'kitchen',
    moduleId: 'kitchen',
  },
  {
    href: '/admin/delivery',
    label: 'Entrega',
    description: '¿Qué envíos salen hoy?',
    iconId: 'truck',
    groupId: 'operacion',
    sidebarTier: 'core',
    planFeature: 'delivery',
    restaurantFeature: 'delivery',
    permission: 'delivery',
    moduleId: 'delivery',
  },
  {
    href: '/admin/delivery/mis-envios',
    label: 'Mis envíos',
    description: 'Mi ruta asignada',
    iconId: 'navigation',
    groupId: 'operacion',
    sidebarTier: 'extended',
    planFeature: 'delivery',
    restaurantFeature: 'delivery',
    permission: 'delivery',
    moduleId: 'delivery',
  },
  {
    href: '/admin/reservations',
    label: 'Reservas',
    description: '¿Quién viene hoy?',
    iconId: 'calendar',
    groupId: 'operacion',
    sidebarTier: 'extended',
    planFeature: 'reservations',
    restaurantFeature: 'reservations',
    permission: 'reservations',
    moduleId: 'reservations',
  },
  {
    href: '/admin/tables',
    label: 'Mesas',
    description: '¿Cómo está armado el salón?',
    iconId: 'grid-3x3',
    groupId: 'operacion',
    sidebarTier: 'extended',
    restaurantFeature: 'tables',
    permission: 'tables',
    moduleId: 'tables',
  },
  {
    href: '/admin/integrations',
    label: 'Apps delivery',
    description: 'PedidosYa, Rappi y Uber Eats',
    iconId: 'plug',
    groupId: 'operacion',
    sidebarTier: 'extended',
    restaurantFeatures: ['orders', 'delivery'],
    permission: 'orders',
    moduleId: 'integrations',
  },
  {
    href: '/admin/comprobantes',
    label: 'Comprobantes',
    description: '¿Qué tickets emití?',
    iconId: 'file-text',
    groupId: 'operacion',
    sidebarTier: 'extended',
    restaurantFeature: 'salon',
    permission: 'salon',
    moduleId: 'salon',
  },
  {
    href: '/admin/negocio',
    label: 'Negocio',
    description: '¿Cómo viene el negocio?',
    iconId: 'heart-pulse',
    groupId: 'negocio',
    sidebarTier: 'core',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/negocio?tab=margenes',
    label: 'Stock y márgenes',
    description: '¿Qué conviene revisar?',
    iconId: 'trending-up',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/negocio?tab=decisiones',
    label: 'Decisiones',
    description: '¿Qué conviene cambiar en la carta?',
    iconId: 'heart-pulse',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/analytics',
    label: '¿Cuánto vendí?',
    description: 'Ventas por período',
    iconId: 'bar-chart-3',
    groupId: 'negocio',
    sidebarTier: 'core',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/packs/customers',
    label: 'Clientes',
    description: '¿A quién conviene llamar?',
    iconId: 'users',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/packs/inventory',
    label: 'Inventario',
    description: '¿Qué me falta comprar?',
    iconId: 'package',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/packs/operations',
    label: 'Operaciones',
    description: '¿Cómo va la operación hoy?',
    iconId: 'chef-hat',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/caja-mayor',
    label: 'Caja del local',
    description: '¿Cómo cierro la caja mayor?',
    iconId: 'wallet',
    groupId: 'negocio',
    sidebarTier: 'extended',
    restaurantFeature: 'orders',
    permission: 'salon',
    requiresMainCash: true,
    moduleId: 'salon',
  },
  {
    href: '/admin/diario',
    label: 'Lo que pasó',
    description: 'Lo reciente en tu local',
    iconId: 'book-open',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/experiments',
    label: 'Pruebas en carta',
    description: 'Probá precios y platos con datos reales',
    iconId: 'flask-conical',
    groupId: 'negocio',
    sidebarTier: 'extended',
    planFeature: 'analytics',
    permission: 'reports',
    moduleId: 'analytics',
  },
  {
    href: '/admin/menu',
    label: 'Menú',
    description: '¿Qué vendés hoy?',
    iconId: 'utensils-crossed',
    groupId: 'ventas',
    sidebarTier: 'core',
    restaurantFeature: 'menu',
    permission: 'menu',
    moduleId: 'menu',
  },
  {
    href: '/admin/builder',
    label: 'Sitio web',
    description: 'Tu canal propio para vender',
    iconId: 'layout-template',
    groupId: 'ventas',
    sidebarTier: 'core',
    restaurantFeatures: ['menu', 'onlineOrdering'],
    permission: 'branding',
    moduleId: 'builder',
  },
  {
    href: '/admin/promotions',
    label: 'Promociones',
    description: 'Traé gente sin regalar el margen a ciegas',
    iconId: 'gift',
    groupId: 'ventas',
    sidebarTier: 'extended',
    planFeature: 'loyalty',
    restaurantFeature: 'loyalty',
    permission: 'promotions',
    moduleId: 'promotions',
  },
  {
    href: '/admin/reviews',
    label: 'Reseñas',
    description: '¿Qué están diciendo de tu local?',
    iconId: 'message-square',
    groupId: 'ventas',
    sidebarTier: 'extended',
    restaurantFeature: 'reviews',
    moduleId: 'reviews',
  },
  {
    href: '/admin/loyalty',
    label: 'Fidelización',
    description: '¿Quién vuelve y a quién conviene cuidar?',
    iconId: 'award',
    groupId: 'ventas',
    sidebarTier: 'extended',
    restaurantFeature: 'loyalty',
    moduleId: 'loyalty',
  },
  {
    href: '/admin/go-live',
    label: 'Arrancar',
    description: '¿Qué me falta para arrancar?',
    iconId: 'rocket',
    groupId: 'config',
    sidebarTier: 'extended',
  },
  {
    href: '/admin/subscription',
    label: 'Plan Bentoo',
    description: 'Tu plan y lo que incluye tu operación',
    iconId: 'credit-card',
    groupId: 'config',
    sidebarTier: 'core',
    permission: 'billing',
  },
  {
    href: '/admin/settings',
    label: 'Ajustes',
    description: 'Datos del local y equipo',
    iconId: 'settings',
    groupId: 'config',
    sidebarTier: 'core',
    permission: 'settings',
  },
];

export const NAV_CATALOG_BY_HREF = new Map(
  NAV_CATALOG.map((entry) => [entry.href, entry]),
);

export function getNavCatalogEntry(href: string): NavCatalogEntry | undefined {
  return NAV_CATALOG_BY_HREF.get(href);
}
