ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "activationCodeHash" TEXT,
ADD COLUMN IF NOT EXISTS "activationCodeExpiresAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "activationCodeAttempts" INTEGER NOT NULL DEFAULT 0;
