import { LabScenarioDefinition } from './scenario.types';

/**
 * Escenario corto closeout: 2 pedidos online hasta DELIVERED+PAID.
 * Lista NO_OPEN_ORDERS_AT_COMPLETE (pizzeria-30m no lo lista a propósito).
 */
export const PIZZERIA_CLOSEOUT_10M_SCENARIO = {
  id: 'pizzeria-closeout-10m',
  version: '1.0.0',
  label: 'Pizzería · closeout limpio · 10 minutos',
  durationMinutes: 10,
  simulatedStartAt: '2026-07-17T23:00:00.000Z',
  defaultSpeed: 20,
  preferredLabProfile: 'ops-core',
  restaurant: {
    type: 'pizzeria',
    channels: ['online'],
  },
  menu: [
    {
      key: 'pizza-muzzarella',
      name: 'Pizza muzzarella',
      price: 8000,
      preparationMinutes: 12,
    },
    {
      key: 'fugazzeta',
      name: 'Fugazzeta',
      price: 9500,
      preparationMinutes: 15,
    },
  ],
  participants: ['client', 'kitchen', 'manager'],
  events: [
    {
      id: 'event.client.order.0001',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0001',
      atMinute: 1,
      priority: 10,
    },
    {
      id: 'event.manager.pay.0001',
      type: 'MANAGER_MARK_ORDER_PAID',
      participantKey: 'manager',
      orderKey: 'order.online.0001',
      atMinute: 2,
      priority: 15,
    },
    {
      id: 'event.kitchen.start.0001',
      type: 'KITCHEN_START_ORDER',
      participantKey: 'kitchen',
      orderKey: 'order.online.0001',
      atMinute: 3,
      priority: 20,
    },
    {
      id: 'event.client.order.0002',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0002',
      atMinute: 3,
      priority: 25,
    },
    {
      id: 'event.kitchen.ready.0001',
      type: 'KITCHEN_READY_ORDER',
      participantKey: 'kitchen',
      orderKey: 'order.online.0001',
      atMinute: 4,
      priority: 20,
    },
    {
      id: 'event.manager.pay.0002',
      type: 'MANAGER_MARK_ORDER_PAID',
      participantKey: 'manager',
      orderKey: 'order.online.0002',
      atMinute: 4,
      priority: 25,
    },
    {
      id: 'event.manager.deliver.0001',
      type: 'MANAGER_MARK_ORDER_DELIVERED',
      participantKey: 'manager',
      orderKey: 'order.online.0001',
      atMinute: 5,
      priority: 20,
    },
    {
      id: 'event.kitchen.start.0002',
      type: 'KITCHEN_START_ORDER',
      participantKey: 'kitchen',
      orderKey: 'order.online.0002',
      atMinute: 6,
      priority: 20,
    },
    {
      id: 'event.kitchen.ready.0002',
      type: 'KITCHEN_READY_ORDER',
      participantKey: 'kitchen',
      orderKey: 'order.online.0002',
      atMinute: 7,
      priority: 20,
    },
    {
      id: 'event.manager.deliver.0002',
      type: 'MANAGER_MARK_ORDER_DELIVERED',
      participantKey: 'manager',
      orderKey: 'order.online.0002',
      atMinute: 8,
      priority: 20,
    },
    {
      id: 'event.simulation.complete',
      type: 'SIMULATION_COMPLETE',
      participantKey: 'system',
      atMinute: 10,
      priority: 100,
    },
  ],
  invariants: [
    'TENANT_SCOPE',
    'ORDER_PREPARATION_CAUSALITY',
    'AUTHORIZED_ACTOR_ACTIONS',
    'EXTERNAL_EFFECTS_BLOCKED',
    'ORDER_STATE_VALIDITY',
    'EXPECTED_INCIDENTS_ONCE',
    'STOCK_NON_NEGATIVE',
    'TIMELINE_CONTIGUOUS',
    'INCIDENT_REPLAY_DETERMINISM',
    'NO_OPEN_ORDERS_AT_COMPLETE',
  ],
} as const satisfies LabScenarioDefinition;
