import { LabScenarioDefinition } from './scenario.types';

/** Escenario corto growth: cupón → pedido online → loyalty → review → builder. */
export const PIZZERIA_GROWTH_10M_SCENARIO = {
  id: 'pizzeria-growth-10m',
  version: '1.0.0',
  label: 'Pizzería · growth · cupón + loyalty + review · 10 minutos',
  durationMinutes: 10,
  simulatedStartAt: '2026-07-17T23:00:00.000Z',
  defaultSpeed: 20,
  preferredLabProfile: 'ops-core',
  restaurant: {
    type: 'pizzeria',
    channels: ['online'],
  },
  menu: [
    {
      key: 'pizza-muzzarella',
      name: 'Pizza muzzarella',
      price: 8000,
      preparationMinutes: 12,
    },
    {
      key: 'fugazzeta',
      name: 'Fugazzeta',
      price: 9500,
      preparationMinutes: 15,
    },
  ],
  participants: ['client', 'manager', 'kitchen'],
  events: [
    {
      id: 'event.coupon.validate.0001',
      type: 'COUPON_VALIDATE',
      participantKey: 'client',
      couponCode: 'LAB10',
      orderAmount: 8000,
      atMinute: 1,
      priority: 10,
    },
    {
      id: 'event.client.order.0001',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0001',
      couponCode: 'LAB10',
      atMinute: 2,
      priority: 15,
    },
    {
      id: 'event.loyalty.enroll.0001',
      type: 'LOYALTY_ENROLL',
      participantKey: 'client',
      customerEmail: 'growth@lab.bentoo.invalid',
      customerName: 'Cliente Growth Lab',
      customerPhone: '+54 11 5555-0400',
      atMinute: 4,
      priority: 20,
    },
    {
      id: 'event.review.create.0001',
      type: 'REVIEW_CREATE',
      participantKey: 'client',
      customerName: 'Cliente Growth Lab',
      customerEmail: 'growth@lab.bentoo.invalid',
      rating: 5,
      comment: 'Pedido Lab con cupón',
      atMinute: 6,
      priority: 25,
    },
    {
      id: 'event.builder.public.0001',
      type: 'BUILDER_PUBLIC_GET',
      participantKey: 'client',
      atMinute: 8,
      priority: 30,
    },
    {
      id: 'event.simulation.complete',
      type: 'SIMULATION_COMPLETE',
      participantKey: 'system',
      atMinute: 10,
      priority: 100,
    },
  ],
  invariants: [
    'TENANT_SCOPE',
    'AUTHORIZED_ACTOR_ACTIONS',
    'EXTERNAL_EFFECTS_BLOCKED',
    'ORDER_STATE_VALIDITY',
    'EXPECTED_INCIDENTS_ONCE',
    'TIMELINE_CONTIGUOUS',
    'INCIDENT_REPLAY_DETERMINISM',
  ],
} as const satisfies LabScenarioDefinition;
