import { LabScenarioDefinition } from './scenario.types';

export const PIZZERIA_FRIDAY_30M_SCENARIO = {
  id: 'pizzeria-30m',
  version: '2.0.0',
  label: 'Pizzería · viernes · 30 minutos',
  durationMinutes: 30,
  simulatedStartAt: '2026-07-17T23:00:00.000Z',
  defaultSpeed: 20,
  restaurant: {
    type: 'pizzeria',
    channels: ['online'],
  },
  menu: [
    {
      key: 'pizza-muzzarella',
      name: 'Pizza muzzarella',
      price: 8000,
      preparationMinutes: 12,
    },
    {
      key: 'fugazzeta',
      name: 'Fugazzeta',
      price: 9500,
      preparationMinutes: 15,
    },
  ],
  participants: ['client', 'kitchen', 'manager'],
  events: [
    {
      id: 'event.client.order.0001',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0001',
      atMinute: 2,
      priority: 10,
    },
    {
      id: 'event.manager.pay.0001',
      type: 'MANAGER_MARK_ORDER_PAID',
      participantKey: 'manager',
      orderKey: 'order.online.0001',
      atMinute: 4,
      priority: 15,
    },
    {
      id: 'event.client.order.0002',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0002',
      atMinute: 6,
      priority: 10,
    },
    {
      id: 'event.client.order.0003',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0003',
      atMinute: 10,
      priority: 10,
    },
    {
      id: 'event.incident.kitchen-delay.0001',
      type: 'INCIDENT_KITCHEN_DELAY',
      participantKey: 'system',
      orderKey: 'order.online.0001',
      atMinute: 11,
      priority: 5,
    },
    {
      id: 'event.kitchen.start.0001',
      type: 'KITCHEN_START_ORDER',
      participantKey: 'kitchen',
      orderKey: 'order.online.0001',
      atMinute: 12,
      priority: 20,
    },
    {
      id: 'event.client.order.0004',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0004',
      atMinute: 13,
      priority: 10,
    },
    {
      id: 'event.kitchen.ready.0001',
      type: 'KITCHEN_READY_ORDER',
      participantKey: 'kitchen',
      orderKey: 'order.online.0001',
      atMinute: 18,
      priority: 20,
    },
    {
      id: 'event.client.order.0005',
      type: 'CLIENT_CREATE_ONLINE_ORDER',
      participantKey: 'client',
      orderKey: 'order.online.0005',
      atMinute: 22,
      priority: 10,
    },
    {
      id: 'event.incident.stockout.0001',
      type: 'INCIDENT_STOCKOUT',
      participantKey: 'manager',
      inventoryItemKey: 'masa',
      atMinute: 24,
      priority: 25,
    },
    {
      id: 'event.simulation.complete',
      type: 'SIMULATION_COMPLETE',
      participantKey: 'system',
      atMinute: 30,
      priority: 100,
    },
  ],
  invariants: [
    'TENANT_SCOPE',
    'ORDER_PREPARATION_CAUSALITY',
    'AUTHORIZED_ACTOR_ACTIONS',
    'EXTERNAL_EFFECTS_BLOCKED',
    'ORDER_STATE_VALIDITY',
    'EXPECTED_INCIDENTS_ONCE',
    'STOCK_NON_NEGATIVE',
    'TIMELINE_CONTIGUOUS',
    'INCIDENT_REPLAY_DETERMINISM',
  ],
} as const satisfies LabScenarioDefinition;
