import { flagshipPhoto } from '../assets/paths';
import type { StoryProfile } from '../types';

const photo = (file: string) => flagshipPhoto('burger-lab', file);

export const burgerLabProfile: StoryProfile = {
  slug: 'burger-lab',
  sortOrder: 3,
  seed: 0x42555247, // BURG
  name: 'Carbón Burger Lab',
  type: 'restaurant',
  cuisine: ['Burgers', 'Smash', 'Cerveza'],
  city: 'Córdoba',
  neighborhood: 'Nueva Córdoba',
  address: 'Bv. San Juan 742',
  phone: '+54 351 468-2290',
  email: 'hola@carbonburgerlab.com.ar',
  instagram: '@carbonburgerlab',
  foundedYear: 2020,
  capacity: 36,
  priceRange: '$$',
  concept: 'Smash burgers a la plancha + birra artesanal',
  ownerName: 'Facundo “Facu” Molina',
  ownerStory:
    'Facu laburó en dark kitchens durante la pandemia y abrió Carbón cuando se cansó de que la burger buena solo existiera en delivery anónimo.',
  whyOpened:
    'Quería un local con nombre, música baja y smash bien hecho — no otra cadena con pan genérico.',
  targetAudience:
    'Universitarios y oficinistas de Nueva Córdoba; delivery fuerte vie–sáb de noche.',
  avgTicket: 14500,
  monthlyOrderTarget: 1100,
  hits: ['Smash Clásica', 'Papas Carbón', 'Combo Lab'],
  problems: [
    'Viernes y sábado 21–23 hs: delivery satura la plancha',
    'A veces falta cheddar el domingo',
    'Lunes mediodía: solo combos rápidos',
  ],
  busyDays: ['friday', 'saturday', 'thursday'],
  slowDays: ['monday', 'sunday'],
  peakHours: [13, 20, 21, 22],
  deadHours: [16, 17],
  hours: {
    monday: { open: '12:00', close: '23:00' },
    tuesday: { open: '12:00', close: '23:00' },
    wednesday: { open: '12:00', close: '23:30' },
    thursday: { open: '12:00', close: '00:00' },
    friday: { open: '12:00', close: '01:00' },
    saturday: { open: '12:00', close: '01:00' },
    sunday: { open: '12:00', close: '22:00' },
  },
  description:
    'Smash burgers a la plancha en Nueva Córdoba, papas propias y birra de barril. Delivery que no miente con los tiempos.',
  aboutTitle: 'Fuego, smash y cero relleno',
  aboutBody:
    'La carne la molimos acá. El pan viene de una panadería de barrio. Si la burger tarda, es porque la plancha está llena — no porque olvidamos el pedido.',
  aboutHighlights: [
    'Smash doble o triple',
    'Papas Carbón',
    'Birra artesanal',
    'Delivery hasta tarde',
  ],
  menu: [
    {
      category: 'Burgers',
      name: 'Smash Clásica',
      description:
        'Doble smash, cheddar, cebolla y salsa de la casa. La que pidió Facu el día 1.',
      price: 8900,
      costPrice: 3100,
      prepMinutes: 12,
      featured: true,
      hitWeight: 12,
      tags: ['burger'],
      image: photo('smash-clasica.jpg'),
    },
    {
      category: 'Burgers',
      name: 'Smash Bacon',
      description: 'Clásica + bacon crocante. Sin dramatizar: bacon de verdad.',
      price: 10200,
      costPrice: 3600,
      prepMinutes: 13,
      hitWeight: 8,
      tags: ['burger'],
      image: photo('smash-bacon.jpg'),
    },
    {
      category: 'Burgers',
      name: 'Lab Picante',
      description:
        'Smash, jalapeño, cheddar y mayo chipotle. Avisa si la querés suave.',
      price: 9800,
      costPrice: 3400,
      prepMinutes: 13,
      hitWeight: 6,
      tags: ['burger'],
      image: photo('smash-bacon.jpg'),
    },
    {
      category: 'Burgers',
      name: 'Veggie Smash',
      description:
        'Medallón de garbanzo y hongos, pan brioche, greens y salsa verde.',
      price: 8600,
      costPrice: 2800,
      prepMinutes: 14,
      hitWeight: 4,
      tags: ['burger', 'veggie'],
      image: photo('veggie.jpg'),
    },
    {
      category: 'Acompañamientos',
      name: 'Papas Carbón',
      description:
        'Corte grueso, sal marina y dip de ajo. Van casi siempre con la Clásica.',
      price: 4500,
      costPrice: 1100,
      prepMinutes: 10,
      featured: true,
      hitWeight: 11,
      tags: ['guarnicion'],
      image: photo('papas-carbon.jpg'),
    },
    {
      category: 'Acompañamientos',
      name: 'Aros de cebolla',
      description: 'Rebozado liviano. Para compartir de a dos.',
      price: 4800,
      costPrice: 1300,
      prepMinutes: 9,
      hitWeight: 5,
      tags: ['guarnicion'],
      image: photo('papas-carbon.jpg'),
    },
    {
      category: 'Combos',
      name: 'Combo Lab',
      description:
        'Smash Clásica + Papas Carbón + gaseosa. El mediodía de oficina.',
      price: 12900,
      costPrice: 4500,
      prepMinutes: 14,
      featured: true,
      hitWeight: 10,
      tags: ['combo'],
      image: photo('combo-lab.jpg'),
    },
    {
      category: 'Combos',
      name: 'Combo Doble Noche',
      description: 'Bacon + papas + birra de barril. Después de las 20.',
      price: 16800,
      costPrice: 6200,
      prepMinutes: 15,
      hitWeight: 7,
      tags: ['combo'],
      image: photo('combo-lab.jpg'),
    },
    {
      category: 'Extras',
      name: 'Extra cheddar',
      description: 'Porque a veces hace falta.',
      price: 900,
      costPrice: 250,
      prepMinutes: 1,
      hitWeight: 3,
      tags: ['extra'],
      image: photo('papas-carbon.jpg'),
    },
    {
      category: 'Extras',
      name: 'Extra bacon',
      description: 'Dos fetas crocantes.',
      price: 1200,
      costPrice: 400,
      prepMinutes: 2,
      hitWeight: 3,
      tags: ['extra'],
      image: photo('papas-carbon.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Birra de barril 500ml',
      description: 'IPA o lager según lo que cargamos esa semana.',
      price: 5200,
      costPrice: 1800,
      prepMinutes: 2,
      hitWeight: 7,
      tags: ['bebida', 'cerveza'],
      image: photo('birra.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Gaseosa 500ml',
      description: 'Línea clásica.',
      price: 2500,
      costPrice: 700,
      prepMinutes: 1,
      hitWeight: 6,
      tags: ['bebida'],
      image: photo('birra.jpg'),
    },
    {
      category: 'Postres',
      name: 'Brownie con helado',
      description: 'Caliente, con bocha de americana. Para cerrar la noche.',
      price: 5600,
      costPrice: 1700,
      prepMinutes: 6,
      hitWeight: 4,
      tags: ['postre'],
      image: photo('brownie.jpg'),
    },
  ],
  staff: [
    { name: 'Facundo Molina', role: 'OWNER', emailLocal: 'facu' },
    { name: 'Marina López', role: 'MANAGER', emailLocal: 'marina' },
    { name: 'Pedro Álvarez', role: 'CHEF', emailLocal: 'pedro' },
    { name: 'Agustina Ríos', role: 'CASHIER', emailLocal: 'agus' },
    { name: 'Leo Funes', role: 'DELIVERY', emailLocal: 'leo' },
    { name: 'Maxi Torres', role: 'DELIVERY', emailLocal: 'maxi' },
  ],
  suppliers: [
    { name: 'Carnes del Centro', category: 'Carnes', contact: '351 422-1188' },
    {
      name: 'Panadería Nueva Córdoba',
      category: 'Panadería',
      contact: '351 433-0091',
    },
    { name: 'Quesos del Valle', category: 'Lácteos', contact: '351 455-7720' },
    {
      name: 'Cervecería Andina Distribución',
      category: 'Bebidas',
      contact: '351 480-3344',
    },
  ],
  promos: [
    {
      code: 'COMBOMED',
      name: 'Combo ejecutivo mediodía',
      description: 'Combo Lab a precio cerrado de 12 a 15 hs.',
      discountPercent: 10,
      daysActive: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    },
    {
      code: 'STUDENT15',
      name: 'Descuento estudiante',
      description: '15% con credencial universitaria, lun–jue.',
      discountPercent: 15,
      daysActive: ['monday', 'tuesday', 'wednesday', 'thursday'],
    },
  ],
  inventory: [
    {
      name: 'Blend smash (kg)',
      unit: 'kg',
      quantity: 22,
      lowStockThreshold: 10,
      linkedDishNames: ['Smash Clásica', 'Smash Bacon'],
    },
    {
      name: 'Cheddar feta',
      unit: 'u',
      quantity: 40,
      lowStockThreshold: 50,
      linkedDishNames: ['Smash Clásica', 'Extra cheddar'],
    },
    {
      name: 'Bacon',
      unit: 'kg',
      quantity: 3.5,
      lowStockThreshold: 2,
      linkedDishNames: ['Smash Bacon', 'Extra bacon'],
    },
    {
      name: 'Papas',
      unit: 'kg',
      quantity: 30,
      lowStockThreshold: 12,
      linkedDishNames: ['Papas Carbón'],
    },
    {
      name: 'Pan brioche',
      unit: 'u',
      quantity: 80,
      lowStockThreshold: 40,
      linkedDishNames: ['Smash Clásica'],
    },
  ],
  tableLayout: {
    areas: [
      { name: 'Salón', tables: [2, 2, 4, 4, 4, 6] },
      { name: 'Barra', tables: [1, 1, 1, 1] },
    ],
  },
  media: {
    logo: photo('logo.png'),
    cover: photo('hero.jpg'),
    hero: photo('hero.jpg'),
    interior: [photo('interior.jpg'), photo('hero.jpg')],
  },
  historyDays: 72,
};
