import { flagshipPhoto } from '../assets/paths';
import type { StoryProfile } from '../types';

const photo = (file: string) => flagshipPhoto('cafe-central', file);

export const cafeCentralProfile: StoryProfile = {
  slug: 'cafe-central',
  sortOrder: 2,
  seed: 0x43414645, // CAFE
  name: 'Taller de Café San Telmo',
  type: 'cafe',
  cuisine: ['Café', 'Brunch', 'Pastelería'],
  city: 'Buenos Aires',
  neighborhood: 'San Telmo',
  address: 'Defensa 982',
  phone: '+54 11 4361-7742',
  email: 'hola@tallerdecafe.com.ar',
  instagram: '@tallerdecafe.st',
  foundedYear: 2021,
  capacity: 28,
  priceRange: '$$',
  concept: 'Café de especialidad con brunch de fin de semana',
  ownerName: 'Valentina Rocha',
  ownerStory:
    'Valentina tostó café en un micro-roaster de Colegiales antes de abrir el taller en San Telmo. Quiere que el barrio tome bien sin pagar precio de hotel.',
  whyOpened:
    'Faltaba un lugar con flat white de verdad, medialunas al horno y mesas para trabajar sin echarte a las dos horas.',
  targetAudience:
    'Vecinos, freelancers, turistas que buscan café bueno; domingo brunch con amigos.',
  avgTicket: 9200,
  monthlyOrderTarget: 1400,
  hits: ['Flat white', 'Medialuna de manteca', 'Tostado completo'],
  problems: [
    'Sábado 11–13 hs: cola en mostrador y demora en brunch',
    'A veces se agota el flat white blend el domingo',
    'Lunes y martes: casi solo take away',
  ],
  busyDays: ['saturday', 'sunday', 'friday'],
  slowDays: ['monday', 'tuesday'],
  peakHours: [9, 10, 11, 12, 17],
  deadHours: [15, 16],
  hours: {
    monday: { open: '08:00', close: '18:00' },
    tuesday: { open: '08:00', close: '18:00' },
    wednesday: { open: '08:00', close: '19:00' },
    thursday: { open: '08:00', close: '19:00' },
    friday: { open: '08:00', close: '20:00' },
    saturday: { open: '09:00', close: '20:00' },
    sunday: { open: '09:00', close: '18:00' },
  },
  description:
    'Café de especialidad en San Telmo: espresso, flat white, pastelería de horno y brunch de fin de semana.',
  aboutTitle: 'Café con oficio',
  aboutBody:
    'Tostamos en pequeños lotes y horneamos medialunas todas las mañanas. El local es chico a propósito: queremos conocerte por el nombre del café que pedís.',
  aboutHighlights: [
    'Granos de especialidad',
    'Medialunas al horno',
    'Brunch sáb–dom',
    'WiFi y enchufes',
  ],
  menu: [
    {
      category: 'Café',
      name: 'Espresso',
      description: 'Doble shot, crema corta. Base de todo lo que hacemos.',
      price: 2800,
      costPrice: 700,
      prepMinutes: 3,
      hitWeight: 7,
      tags: ['cafe'],
      image: photo('espresso.jpg'),
    },
    {
      category: 'Café',
      name: 'Flat white',
      description:
        'El más pedido. Microespuma, blend de la casa. Pedilo sin azúcar primero.',
      price: 4200,
      costPrice: 1100,
      prepMinutes: 5,
      featured: true,
      hitWeight: 12,
      tags: ['cafe'],
      image: photo('flat-white.jpg'),
    },
    {
      category: 'Café',
      name: 'Filtro V60',
      description:
        'Origen rotativo. Te contamos en el mostrador qué está cayendo esta semana.',
      price: 4800,
      costPrice: 1400,
      prepMinutes: 6,
      hitWeight: 5,
      tags: ['cafe'],
      image: photo('espresso.jpg'),
    },
    {
      category: 'Café',
      name: 'Cold brew',
      description: 'Extracción 16 hs. Ideal después de las 15.',
      price: 4500,
      costPrice: 1200,
      prepMinutes: 2,
      hitWeight: 4,
      tags: ['cafe'],
      image: photo('espresso.jpg'),
    },
    {
      category: 'Pastelería',
      name: 'Medialuna de manteca',
      description: 'Horno de la mañana. Quedan pocas después de las 11.',
      price: 1800,
      costPrice: 450,
      prepMinutes: 1,
      featured: true,
      hitWeight: 11,
      tags: ['pasteleria'],
      image: photo('medialuna.jpg'),
    },
    {
      category: 'Pastelería',
      name: 'Cookie de chocolate',
      description: 'Bordes crocantes, centro blando. Con sal marina.',
      price: 3200,
      costPrice: 900,
      prepMinutes: 1,
      hitWeight: 6,
      tags: ['pasteleria'],
      image: photo('cookie.jpg'),
    },
    {
      category: 'Pastelería',
      name: 'Budín de limón',
      description: 'Porción del día. Ideal con filtro.',
      price: 3600,
      costPrice: 1000,
      prepMinutes: 1,
      hitWeight: 4,
      tags: ['pasteleria'],
      image: photo('cookie.jpg'),
    },
    {
      category: 'Brunch',
      name: 'Tostado completo',
      description:
        'Pan de masa madre, huevos, palta, queso fresco y greens. Fin de semana.',
      price: 9800,
      costPrice: 3200,
      prepMinutes: 14,
      featured: true,
      hitWeight: 10,
      tags: ['brunch'],
      image: photo('tostado.jpg'),
    },
    {
      category: 'Brunch',
      name: 'Bowl de yogurt y granola',
      description: 'Yogurt natural, granola tostada, fruta de estación y miel.',
      price: 7200,
      costPrice: 2400,
      prepMinutes: 8,
      hitWeight: 5,
      tags: ['brunch'],
      image: photo('yogurt-bowl.jpg'),
    },
    {
      category: 'Brunch',
      name: 'Avocado toast',
      description: 'Palta, limón, semillas y un huevo poche si lo pedís.',
      price: 8500,
      costPrice: 2800,
      prepMinutes: 10,
      hitWeight: 7,
      tags: ['brunch'],
      image: photo('tostado.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Jugo exprimido naranja',
      description: 'Al momento. Sin azúcar.',
      price: 4200,
      costPrice: 1400,
      prepMinutes: 4,
      hitWeight: 5,
      tags: ['bebida'],
      image: photo('jugo.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Limonada casera',
      description: 'Con menta. Jarra chica para compartir.',
      price: 3800,
      costPrice: 900,
      prepMinutes: 3,
      hitWeight: 4,
      tags: ['bebida'],
      image: photo('jugo.jpg'),
    },
  ],
  staff: [
    { name: 'Valentina Rocha', role: 'OWNER', emailLocal: 'vale' },
    { name: 'Julián Paz', role: 'MANAGER', emailLocal: 'julian' },
    { name: 'Camila Soto', role: 'CASHIER', emailLocal: 'cami' },
    { name: 'Bruno Iglesias', role: 'CHEF', emailLocal: 'bruno' },
    { name: 'Inés Vargas', role: 'WAITER', emailLocal: 'ines' },
  ],
  suppliers: [
    {
      name: 'Micro-tostaduría Norte',
      category: 'Café',
      contact: '11 4777-8821',
    },
    {
      name: 'Lácteos La Estancia',
      category: 'Lácteos',
      contact: '11 4222-1003',
    },
    {
      name: 'Frutas del Mercado San Telmo',
      category: 'Frutas',
      contact: '11 4300-5512',
    },
    { name: 'Harinas del Sur', category: 'Panadería', contact: '11 4666-2290' },
  ],
  promos: [
    {
      code: 'HAPPYCAFE',
      name: 'Happy Hour café',
      description: '15% en bebidas de café de 15 a 17 hs de lun a jue.',
      discountPercent: 15,
      daysActive: ['monday', 'tuesday', 'wednesday', 'thursday'],
    },
    {
      code: 'BRUNCH2',
      name: 'Brunch para dos',
      description: 'Dos brunch + dos flat white con precio cerrado sáb–dom.',
      discountPercent: 12,
      daysActive: ['saturday', 'sunday'],
    },
  ],
  inventory: [
    {
      name: 'Blend flat white (kg)',
      unit: 'kg',
      quantity: 4.2,
      lowStockThreshold: 3,
      linkedDishNames: ['Flat white'],
    },
    {
      name: 'Medialunas stock mañana',
      unit: 'u',
      quantity: 28,
      lowStockThreshold: 40,
      linkedDishNames: ['Medialuna de manteca'],
    },
    {
      name: 'Leche entera (L)',
      unit: 'L',
      quantity: 18,
      lowStockThreshold: 8,
      linkedDishNames: ['Flat white'],
    },
    {
      name: 'Palta',
      unit: 'u',
      quantity: 12,
      lowStockThreshold: 8,
      linkedDishNames: ['Avocado toast', 'Tostado completo'],
    },
    {
      name: 'Huevos',
      unit: 'u',
      quantity: 60,
      lowStockThreshold: 24,
      linkedDishNames: ['Tostado completo'],
    },
  ],
  tableLayout: {
    areas: [
      { name: 'Ventana', tables: [2, 2, 2] },
      { name: 'Salón', tables: [2, 4, 4, 4] },
      { name: 'Barra', tables: [1, 1, 1, 1] },
    ],
  },
  media: {
    logo: photo('logo.png'),
    cover: photo('hero.jpg'),
    hero: photo('hero.jpg'),
    interior: [photo('interior.jpg'), photo('hero.jpg')],
  },
  historyDays: 70,
};
