import { flagshipPhoto } from '../assets/paths';
import type { StoryProfile } from '../types';

const photo = (file: string) => flagshipPhoto('la-parrilla', file);

export const laParrillaProfile: StoryProfile = {
  slug: 'la-parrilla',
  sortOrder: 1,
  seed: 0x50415252, // PARR
  name: 'Fuego de Palermo',
  type: 'restaurant',
  cuisine: ['Argentina', 'Parrilla', 'Asado'],
  city: 'Buenos Aires',
  neighborhood: 'Palermo',
  address: 'Thames 1847',
  phone: '+54 11 4832-6091',
  email: 'hola@fuegodepalermo.com.ar',
  instagram: '@fuegodepalermo',
  foundedYear: 2019,
  capacity: 48,
  priceRange: '$$$',
  concept: 'Parrilla de barrio con patio y cortes a la leña',
  ownerName: 'Martín Aguirre',
  ownerStory:
    'Martín cocinó 12 años en parrillas de Palermo Hollywood. En 2019 abrió su propio local con un patio chico y la receta de chimichurri de su abuelo.',
  whyOpened:
    'Quería un lugar donde el asado no compita con música fuerte ni mesas apuradas: cortes buenos, tiempo justo, vecinos que vuelven.',
  targetAudience:
    'Parejas y grupos de amigos del barrio; turistas que buscan parrilla auténtica sin cadena.',
  avgTicket: 28500,
  monthlyOrderTarget: 920,
  hits: [
    'Bife de chorizo (400g)',
    'Provoleta a la parrilla',
    'Milanesa napolitana',
  ],
  problems: [
    'Los viernes la cocina se demora 15–20 min en hora pico',
    'El chorizo artesanal a veces se agota el sábado',
    'Domingo mediodía: muchas reservas familiares, poco delivery',
  ],
  busyDays: ['friday', 'saturday', 'sunday'],
  slowDays: ['monday', 'tuesday'],
  peakHours: [13, 14, 21, 22],
  deadHours: [16, 17],
  hours: {
    monday: { open: '12:00', close: '15:30' },
    tuesday: { open: '12:00', close: '23:30' },
    wednesday: { open: '12:00', close: '23:30' },
    thursday: { open: '12:00', close: '23:30' },
    friday: { open: '12:00', close: '00:30' },
    saturday: { open: '12:00', close: '00:30' },
    sunday: { open: '12:00', close: '16:30' },
  },
  description:
    'Parrilla de barrio en Palermo con patio, cortes a punto y chimichurri de la casa. Sin cadena, sin apuro.',
  aboutTitle: 'El fuego que nos define',
  aboutBody:
    'Abrimos en 2019 con una parrilla chica y un patio. Hoy seguimos comprando carne en el mismo proveedor de Mataderos y cocinamos como nos gusta comer: sin apuro, con buen punto.',
  aboutHighlights: [
    'Cortes a la leña',
    'Patio techado para 20',
    'Chimichurri de la casa',
    'Reservas por WhatsApp y web',
  ],
  menu: [
    {
      category: 'Entradas',
      name: 'Provoleta a la parrilla',
      description:
        'Provoleta gruesa, orégano y chimichurri. Sale cuando está burbujeando.',
      price: 9200,
      costPrice: 3400,
      prepMinutes: 12,
      featured: true,
      hitWeight: 9,
      tags: ['entrada', 'queso'],
      image: photo('provoleta.jpg'),
    },
    {
      category: 'Entradas',
      name: 'Choripán de la casa',
      description:
        'Chorizo que hacemos con el carnicero, pan de campo tostado y salsa criolla.',
      price: 6800,
      costPrice: 2200,
      prepMinutes: 10,
      hitWeight: 7,
      tags: ['entrada'],
      image: photo('choripan.jpg'),
    },
    {
      category: 'Entradas',
      name: 'Empanadas de carne (2 u.)',
      description:
        'Horno, jugosas, con un toque de comino. Como las de domingo en familia.',
      price: 5400,
      costPrice: 1800,
      prepMinutes: 8,
      hitWeight: 6,
      tags: ['entrada'],
      image: photo('empanadas.jpg'),
    },
    {
      category: 'Asados',
      name: 'Bife de chorizo (400g)',
      description:
        'El corte que más pedimos. Punto a elección, con papas o ensalada.',
      price: 19800,
      costPrice: 10200,
      prepMinutes: 25,
      featured: true,
      hitWeight: 12,
      tags: ['parrilla', 'carne'],
      image: photo('bife-chorizo.jpg'),
    },
    {
      category: 'Asados',
      name: 'Entraña (350g)',
      description:
        'Marinada suave, sellada fuerte. Ideal para compartir de a dos con guarnición.',
      price: 17200,
      costPrice: 8600,
      prepMinutes: 22,
      hitWeight: 8,
      tags: ['parrilla'],
      image: photo('entrana.jpg'),
    },
    {
      category: 'Asados',
      name: 'Tira de asado (500g)',
      description:
        'Cocción lenta al costado de la parrilla. Pedila si te gusta con hueso.',
      price: 14900,
      costPrice: 6400,
      prepMinutes: 28,
      hitWeight: 7,
      tags: ['parrilla'],
      image: photo('entrana.jpg'),
    },
    {
      category: 'Achuras',
      name: 'Morcilla vasca',
      description:
        'Con cebolla caramelizada. Porción para picar antes del corte.',
      price: 7600,
      costPrice: 2500,
      prepMinutes: 15,
      hitWeight: 5,
      tags: ['achura'],
      image: photo('achuras.jpg'),
    },
    {
      category: 'Achuras',
      name: 'Chinchulines crocantes',
      description:
        'Bien dorados, sin aceite de más. Pedilos temprano: se van primero.',
      price: 8100,
      costPrice: 2700,
      prepMinutes: 18,
      hitWeight: 4,
      tags: ['achura'],
      image: photo('achuras.jpg'),
    },
    {
      category: 'Guarniciones',
      name: 'Papas rústicas',
      description: 'Con cáscara, ají molido y un golpe de limón.',
      price: 5400,
      costPrice: 1300,
      prepMinutes: 12,
      hitWeight: 8,
      tags: ['guarnicion'],
      image: photo('papas-rusticas.jpg'),
    },
    {
      category: 'Guarniciones',
      name: 'Ensalada de la casa',
      description:
        'Lechuga, tomate, cebolla y aceite de oliva. Simple y fresca.',
      price: 4900,
      costPrice: 1200,
      prepMinutes: 8,
      hitWeight: 5,
      tags: ['guarnicion'],
      image: photo('papas-rusticas.jpg'),
    },
    {
      category: 'Milanesas',
      name: 'Milanesa napolitana',
      description:
        'Casera, con jamón, mozzarella y salsa. Sale con papas si la pedís.',
      price: 12400,
      costPrice: 4500,
      prepMinutes: 20,
      hitWeight: 9,
      tags: ['milanesa'],
      image: photo('milanesa.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Malbec copa',
      description: 'Etiqueta de Mendoza que rotamos cada dos meses.',
      price: 4800,
      costPrice: 1500,
      prepMinutes: 2,
      hitWeight: 6,
      tags: ['bebida', 'vino'],
      image: photo('malbec.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Agua con gas 500ml',
      description: 'Bien fría.',
      price: 2200,
      costPrice: 600,
      prepMinutes: 1,
      hitWeight: 4,
      tags: ['bebida'],
      image: photo('malbec.jpg'),
    },
    {
      category: 'Postres',
      name: 'Flan casero con dulce de leche',
      description: 'Receta de la abuela de Martín. Sin atajos.',
      price: 5800,
      costPrice: 1600,
      prepMinutes: 5,
      hitWeight: 6,
      tags: ['postre'],
      image: photo('flan.jpg'),
    },
  ],
  staff: [
    { name: 'Martín Aguirre', role: 'OWNER', emailLocal: 'martin' },
    { name: 'Lucía Fernández', role: 'MANAGER', emailLocal: 'lucia' },
    { name: 'Diego Roldán', role: 'CHEF', emailLocal: 'diego' },
    { name: 'Sofía Méndez', role: 'WAITER', emailLocal: 'sofia' },
    { name: 'Tomás Quiroga', role: 'WAITER', emailLocal: 'tomas' },
    { name: 'Nahuel Cruz', role: 'DELIVERY', emailLocal: 'nahuel' },
  ],
  suppliers: [
    {
      name: 'Carnicería Don Julio (Mataderos)',
      category: 'Carnes',
      contact: '11 4682-1100',
    },
    {
      name: 'Verdulería Thames',
      category: 'Verduras',
      contact: '11 4831-2211',
    },
    {
      name: 'Distribuidora Sur Bebidas',
      category: 'Bebidas',
      contact: '11 4555-0099',
    },
    {
      name: 'Panadería El Horno de Villa Crespo',
      category: 'Panadería',
      contact: '11 4855-3344',
    },
  ],
  promos: [
    {
      code: 'MARTES2X1',
      name: '2x1 en empanadas los martes',
      description: 'De 12 a 16 hs, en local y take away.',
      discountPercent: 15,
      daysActive: ['tuesday'],
    },
    {
      code: 'ALMUERZO',
      name: 'Combo mediodía',
      description: 'Corte + guarnición + gaseosa con precio cerrado.',
      discountPercent: 10,
      daysActive: ['monday', 'tuesday', 'wednesday', 'thursday'],
    },
  ],
  inventory: [
    {
      name: 'Bife de chorizo (kg)',
      unit: 'kg',
      quantity: 18,
      lowStockThreshold: 8,
      linkedDishNames: ['Bife de chorizo (400g)'],
    },
    {
      name: 'Chorizo artesanal',
      unit: 'u',
      quantity: 14,
      lowStockThreshold: 20,
      linkedDishNames: ['Choripán de la casa'],
    },
    {
      name: 'Papas',
      unit: 'kg',
      quantity: 22,
      lowStockThreshold: 10,
      linkedDishNames: ['Papas rústicas'],
    },
    {
      name: 'Provoleta',
      unit: 'kg',
      quantity: 6,
      lowStockThreshold: 3,
      linkedDishNames: ['Provoleta a la parrilla'],
    },
    {
      name: 'Malbec botella',
      unit: 'u',
      quantity: 28,
      lowStockThreshold: 12,
      linkedDishNames: ['Malbec copa'],
    },
  ],
  tableLayout: {
    areas: [
      { name: 'Salón', tables: [2, 2, 4, 4, 4, 6] },
      { name: 'Patio', tables: [2, 4, 4, 6] },
    ],
  },
  media: {
    logo: photo('logo.png'),
    cover: photo('hero.jpg'),
    hero: photo('hero.jpg'),
    interior: [photo('interior.jpg'), photo('hero.jpg')],
  },
  historyDays: 75,
};
