import { flagshipPhoto } from '../assets/paths';
import type { StoryProfile } from '../types';

const photo = (file: string) => flagshipPhoto('pizza-artesanal', file);

export const pizzaArtesanalProfile: StoryProfile = {
  slug: 'pizza-artesanal',
  sortOrder: 4,
  seed: 0x50495a5a, // PIZZ
  name: 'Horno Villa Crespo',
  type: 'restaurant',
  cuisine: ['Pizza', 'Empanadas', 'Italiana'],
  city: 'Buenos Aires',
  neighborhood: 'Villa Crespo',
  address: 'Camargo 712',
  phone: '+54 11 4857-3340',
  email: 'hola@hornovillacrespo.com.ar',
  instagram: '@hornovillacrespo',
  foundedYear: 2016,
  capacity: 42,
  priceRange: '$$',
  concept: 'Pizza a la piedra de barrio, masa madre y horno de barro',
  ownerName: 'Diego “Dieguito” Ferraro',
  ownerStory:
    'Diego aprendió a amasar con su viejo en una pizzería de Corrientes. En 2016 abrió el Horno en Villa Crespo para hacer la pizza que le gustaba comer: masa larga, queso de verdad, sin apuro.',
  whyOpened:
    'Había demasiadas pizzas rápidas y pocas con masa que respire. Quería un local donde el barrio se sienta en casa.',
  targetAudience:
    'Familias del barrio, grupos de amigos, delivery fuerte vie–dom.',
  avgTicket: 16800,
  monthlyOrderTarget: 980,
  hits: [
    'Mozzarella a la piedra',
    'Fugazzeta rellena',
    'Empanadas de carne (media docena)',
  ],
  problems: [
    'Viernes noche: el horno no da abasto entre 21 y 23',
    'A veces se agota la mozzarella de tambo el domingo',
    'Martes mediodía: solo take away y poco salón',
  ],
  busyDays: ['friday', 'saturday', 'sunday'],
  slowDays: ['monday', 'tuesday'],
  peakHours: [13, 21, 22],
  deadHours: [16, 17],
  hours: {
    monday: { open: '12:00', close: '15:00' },
    tuesday: { open: '12:00', close: '23:00' },
    wednesday: { open: '12:00', close: '23:00' },
    thursday: { open: '12:00', close: '23:30' },
    friday: { open: '12:00', close: '00:30' },
    saturday: { open: '12:00', close: '00:30' },
    sunday: { open: '12:00', close: '23:00' },
  },
  description:
    'Pizza a la piedra en Villa Crespo: masa madre, mozzarella de tambo y horno de barro. Empanadas y fainá para acompañar.',
  aboutTitle: 'Masa que espera, pizza que vuelve',
  aboutBody:
    'La masa fermenta 48 horas. El queso viene de un tambo de Mercedes. Si la mozzarella tarda un poco más, es porque el horno está a full — no porque olvidamos tu pedido.',
  aboutHighlights: [
    'Horno de barro',
    'Masa madre 48 hs',
    'Empanadas al horno',
    'Delivery al barrio',
  ],
  menu: [
    {
      category: 'Pizzas',
      name: 'Mozzarella a la piedra',
      description:
        'Clásica grande: salsa de la casa, mozzarella de tambo y aceitunas. La que pidió Diego el día 1.',
      price: 11800,
      costPrice: 4200,
      prepMinutes: 18,
      featured: true,
      hitWeight: 12,
      tags: ['pizza'],
      image: photo('mozzarella.jpg'),
    },
    {
      category: 'Pizzas',
      name: 'Napolitana',
      description:
        'Mozzarella, rodajas de tomate, ajo y orégano. Bien argentina.',
      price: 13900,
      costPrice: 4800,
      prepMinutes: 18,
      hitWeight: 8,
      tags: ['pizza'],
      image: photo('napolitana.jpg'),
    },
    {
      category: 'Pizzas',
      name: 'Fugazzeta rellena',
      description:
        'Cebolla blanca, mozzarella por todos lados. Para compartir de a dos (o no).',
      price: 16500,
      costPrice: 5600,
      prepMinutes: 22,
      featured: true,
      hitWeight: 10,
      tags: ['pizza'],
      image: photo('fugazzeta.jpg'),
    },
    {
      category: 'Pizzas',
      name: 'Provolone y rúcula',
      description:
        'Provolone derretido, rúcula fresca y aceite de oliva al salir.',
      price: 14800,
      costPrice: 5200,
      prepMinutes: 18,
      hitWeight: 5,
      tags: ['pizza'],
      image: photo('provolone.jpg'),
    },
    {
      category: 'Pizzas',
      name: 'Calabresa',
      description:
        'Mozzarella y longaniza picante en rodajas. Avisa si la querés suave.',
      price: 14200,
      costPrice: 5000,
      prepMinutes: 18,
      hitWeight: 6,
      tags: ['pizza'],
      image: photo('calabresa.jpg'),
    },
    {
      category: 'Empanadas',
      name: 'Empanadas de carne (media docena)',
      description: 'Horno de barro, carne cortada a cuchillo, cebolla y huevo.',
      price: 7800,
      costPrice: 2800,
      prepMinutes: 12,
      featured: true,
      hitWeight: 9,
      tags: ['empanada'],
      image: photo('empanadas.jpg'),
    },
    {
      category: 'Empanadas',
      name: 'Empanadas jamón y queso (media docena)',
      description: 'Clásicas del horno. Van bien con la mozzarella.',
      price: 7200,
      costPrice: 2400,
      prepMinutes: 12,
      hitWeight: 5,
      tags: ['empanada'],
      image: photo('empanadas.jpg'),
    },
    {
      category: 'Acompañamientos',
      name: 'Fainá',
      description:
        'Porción clásica de garbanzo. Para poner arriba de la pizza o al lado.',
      price: 1800,
      costPrice: 400,
      prepMinutes: 8,
      hitWeight: 6,
      tags: ['guarnicion'],
      image: photo('faina.jpg'),
    },
    {
      category: 'Acompañamientos',
      name: 'Ensalada mixta',
      description: 'Lechuga, tomate y cebolla. Cuando hace falta equilibrar.',
      price: 4200,
      costPrice: 1200,
      prepMinutes: 6,
      hitWeight: 3,
      tags: ['ensalada'],
      image: photo('faina.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Gaseosa 1.5L',
      description: 'Línea clásica para la mesa.',
      price: 3200,
      costPrice: 900,
      prepMinutes: 1,
      hitWeight: 7,
      tags: ['bebida'],
      image: photo('gaseosa.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Cerveza artesanal 473ml',
      description: 'Lager o IPA según lo que cargamos esa semana.',
      price: 4800,
      costPrice: 1600,
      prepMinutes: 1,
      hitWeight: 5,
      tags: ['bebida', 'cerveza'],
      image: photo('birra.jpg'),
    },
    {
      category: 'Postres',
      name: 'Flan casero',
      description: 'Con dulce de leche. Para cerrar la noche sin drama.',
      price: 4200,
      costPrice: 1100,
      prepMinutes: 4,
      hitWeight: 4,
      tags: ['postre'],
      image: photo('flan.jpg'),
    },
  ],
  staff: [
    { name: 'Diego Ferraro', role: 'OWNER', emailLocal: 'diego' },
    { name: 'Laura Méndez', role: 'MANAGER', emailLocal: 'laura' },
    { name: 'Tito Ramírez', role: 'CHEF', emailLocal: 'tito' },
    { name: 'Sofía Acosta', role: 'WAITER', emailLocal: 'sofia' },
    { name: 'Bruno Paz', role: 'CASHIER', emailLocal: 'bruno' },
    { name: 'Nico Vega', role: 'DELIVERY', emailLocal: 'nico' },
  ],
  suppliers: [
    { name: 'Harinas del Sur', category: 'Harinas', contact: '11 4567-2210' },
    { name: 'Lácteos Mercedes', category: 'Lácteos', contact: '11 4788-0091' },
    {
      name: 'Verduras Villa Crespo',
      category: 'Verduras',
      contact: '11 4855-3344',
    },
    { name: 'Carnes Camargo', category: 'Carnes', contact: '11 4857-1122' },
  ],
  promos: [
    {
      code: '2X1MARTES',
      name: '2x1 empanadas martes',
      description: 'Media docena al precio de una, solo martes.',
      discountPercent: 50,
      daysActive: ['tuesday'],
    },
    {
      code: 'FAMILIA15',
      name: 'Mesa familiar',
      description: '15% en pizzas grandes viernes y sábado antes de las 20.',
      discountPercent: 15,
      daysActive: ['friday', 'saturday'],
    },
  ],
  inventory: [
    {
      name: 'Mozzarella (kg)',
      unit: 'kg',
      quantity: 18,
      lowStockThreshold: 8,
      linkedDishNames: ['Mozzarella a la piedra', 'Fugazzeta rellena'],
    },
    {
      name: 'Harina 000 (kg)',
      unit: 'kg',
      quantity: 40,
      lowStockThreshold: 15,
      linkedDishNames: ['Mozzarella a la piedra'],
    },
    {
      name: 'Cebolla (kg)',
      unit: 'kg',
      quantity: 6,
      lowStockThreshold: 8,
      linkedDishNames: ['Fugazzeta rellena'],
    },
    {
      name: 'Carne empanada (kg)',
      unit: 'kg',
      quantity: 8,
      lowStockThreshold: 4,
      linkedDishNames: ['Empanadas de carne (media docena)'],
    },
    {
      name: 'Longaniza (kg)',
      unit: 'kg',
      quantity: 3,
      lowStockThreshold: 2,
      linkedDishNames: ['Calabresa'],
    },
  ],
  tableLayout: {
    areas: [
      { name: 'Salón', tables: [2, 2, 4, 4, 4, 6, 6] },
      { name: 'Vereda', tables: [2, 2, 4] },
    ],
  },
  media: {
    logo: photo('logo.png'),
    cover: photo('hero.jpg'),
    hero: photo('hero.jpg'),
    interior: [photo('interior.jpg'), photo('hero.jpg')],
  },
  historyDays: 72,
};
