import { flagshipPhoto } from '../assets/paths';
import type { StoryProfile } from '../types';

const photo = (file: string) => flagshipPhoto('sushi-express', file);

export const sushiExpressProfile: StoryProfile = {
  slug: 'sushi-express',
  sortOrder: 5,
  seed: 0x53555348, // SUSH
  name: 'Kaito Centro',
  type: 'restaurant',
  cuisine: ['Japonesa', 'Sushi', 'Fusión'],
  city: 'Rosario',
  neighborhood: 'Centro',
  address: 'Córdoba 1010',
  phone: '+54 341 456-2290',
  email: 'hola@kaitocentro.com.ar',
  instagram: '@kaitocentro',
  foundedYear: 2018,
  capacity: 38,
  priceRange: '$$',
  concept: 'Sushi fresco del día + delivery exprés en el Centro de Rosario',
  ownerName: 'Ayumi “Ayu” Watanabe',
  ownerStory:
    'Ayu llegó de Osaka a Rosario por una beca y se quedó por el río. Abrió Kaito cuando se cansó de que el “sushi express” del barrio fuera solo arroz frío y wasabi de tubo.',
  whyOpened:
    'Quería un local chico, limpio, con pescado del día y tiempos de delivery que se cumplan.',
  targetAudience:
    'Oficinistas del centro, parejas, delivery fuerte jue–sáb de noche.',
  avgTicket: 15200,
  monthlyOrderTarget: 860,
  hits: ['Philadelphia roll', 'Sashimi mix 12 pzas', 'Nigiri combo'],
  problems: [
    'Jueves a sábado 20–22 hs: delivery satura la barra de rolls',
    'A veces falta salmón fresco el domingo',
    'Lunes mediodía: casi solo take away de menú ejecutivo',
  ],
  busyDays: ['thursday', 'friday', 'saturday'],
  slowDays: ['monday', 'sunday'],
  peakHours: [13, 20, 21, 22],
  deadHours: [16, 17],
  hours: {
    monday: { open: '11:30', close: '15:00' },
    tuesday: { open: '11:30', close: '22:30' },
    wednesday: { open: '11:30', close: '22:30' },
    thursday: { open: '11:30', close: '23:00' },
    friday: { open: '11:30', close: '23:30' },
    saturday: { open: '12:00', close: '23:30' },
    sunday: { open: '12:00', close: '16:00' },
  },
  description:
    'Sushi fresco en el Centro de Rosario: rolls, sashimi y nigiri del día. Delivery que respeta el reloj.',
  aboutTitle: 'Fresco, limpio, sin teatro',
  aboutBody:
    'El pescado llega a la mañana. Los rolls se arman a pedido. Si el delivery tarda, es porque la barra está llena — no porque olvidamos el pedido en un rincón.',
  aboutHighlights: [
    'Pescado del día',
    'Rolls a pedido',
    'Sashimi premium',
    'Delivery exprés Centro',
  ],
  menu: [
    {
      category: 'Rolls',
      name: 'Philadelphia roll',
      description:
        'Salmón, queso crema y palta. El hit del mediodía y de la noche.',
      price: 9800,
      costPrice: 3400,
      prepMinutes: 14,
      featured: true,
      hitWeight: 12,
      tags: ['roll'],
      image: photo('philadelphia.jpg'),
    },
    {
      category: 'Rolls',
      name: 'Spicy tuna',
      description:
        'Atún picante, sésamo y mayo spicy. Avisa si la querés suave.',
      price: 10200,
      costPrice: 3600,
      prepMinutes: 14,
      hitWeight: 8,
      tags: ['roll'],
      image: photo('spicy-tuna.jpg'),
    },
    {
      category: 'Rolls',
      name: 'California roll',
      description: 'Kanikama, palta y pepino. Clásico que nunca falla.',
      price: 8600,
      costPrice: 2800,
      prepMinutes: 12,
      hitWeight: 6,
      tags: ['roll'],
      image: photo('california.jpg'),
    },
    {
      category: 'Rolls',
      name: 'Salmon avocado',
      description: 'Salmón fresco y palta. Sin relleno de más.',
      price: 9400,
      costPrice: 3200,
      prepMinutes: 13,
      hitWeight: 7,
      tags: ['roll'],
      image: photo('salmon-avo.jpg'),
    },
    {
      category: 'Sashimi',
      name: 'Sashimi mix 12 pzas',
      description: 'Salmón, atún y pez blanco. Cortes limpios, sin teatro.',
      price: 14500,
      costPrice: 5800,
      prepMinutes: 10,
      featured: true,
      hitWeight: 10,
      tags: ['sashimi'],
      image: photo('sashimi.jpg'),
    },
    {
      category: 'Sashimi',
      name: 'Sashimi salmón 8 pzas',
      description: 'Solo salmón, cuando querés ir directo.',
      price: 11800,
      costPrice: 4800,
      prepMinutes: 8,
      hitWeight: 5,
      tags: ['sashimi'],
      image: photo('sashimi.jpg'),
    },
    {
      category: 'Nigiri',
      name: 'Nigiri combo',
      description: '8 piezas del chef: salmón, atún, langostino y pez blanco.',
      price: 11800,
      costPrice: 4500,
      prepMinutes: 12,
      featured: true,
      hitWeight: 9,
      tags: ['nigiri'],
      image: photo('nigiri.jpg'),
    },
    {
      category: 'Entradas',
      name: 'Edamame',
      description: 'Sal marina. Para abrir mientras llega el sushi.',
      price: 4200,
      costPrice: 1100,
      prepMinutes: 6,
      hitWeight: 4,
      tags: ['entrada'],
      image: photo('edamame.jpg'),
    },
    {
      category: 'Entradas',
      name: 'Gyozas (6 u.)',
      description: 'Cerdo y verdura, selladas a la plancha.',
      price: 6800,
      costPrice: 2200,
      prepMinutes: 10,
      hitWeight: 5,
      tags: ['entrada'],
      image: photo('gyozas.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Agua mineral 500ml',
      description: 'Sin gas.',
      price: 1800,
      costPrice: 400,
      prepMinutes: 1,
      hitWeight: 6,
      tags: ['bebida'],
      image: photo('agua.jpg'),
    },
    {
      category: 'Bebidas',
      name: 'Té verde frío',
      description: 'Hecho acá, sin azúcar de más.',
      price: 2800,
      costPrice: 600,
      prepMinutes: 2,
      hitWeight: 4,
      tags: ['bebida'],
      image: photo('te-verde.jpg'),
    },
    {
      category: 'Postres',
      name: 'Mochi de té matcha',
      description: 'Dos unidades. Dulce suave para cerrar.',
      price: 4800,
      costPrice: 1400,
      prepMinutes: 3,
      hitWeight: 3,
      tags: ['postre'],
      image: photo('mochi.jpg'),
    },
  ],
  staff: [
    { name: 'Ayumi Watanabe', role: 'OWNER', emailLocal: 'ayu' },
    { name: 'Martín Sosa', role: 'MANAGER', emailLocal: 'martin' },
    { name: 'Kenji Okada', role: 'CHEF', emailLocal: 'kenji' },
    { name: 'Lucía Bianchi', role: 'WAITER', emailLocal: 'lucia' },
    { name: 'Pablo Ruiz', role: 'CASHIER', emailLocal: 'pablo' },
    { name: 'Tomás Gil', role: 'DELIVERY', emailLocal: 'tomas' },
  ],
  suppliers: [
    {
      name: 'Pescadería Río Paraná',
      category: 'Pescados',
      contact: '341 422-1188',
    },
    { name: 'Arroz Premium Sur', category: 'Secos', contact: '341 433-0091' },
    { name: 'Verduras Centro', category: 'Verduras', contact: '341 455-7720' },
    {
      name: 'Importadora Nippon SA',
      category: 'Importados',
      contact: '341 480-3344',
    },
  ],
  promos: [
    {
      code: 'MEDIODIA',
      name: 'Menú ejecutivo mediodía',
      description: 'Philadelphia + té o agua, lun–vie 12–15 hs.',
      discountPercent: 12,
      daysActive: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    },
    {
      code: 'COMBO2ROLLS',
      name: '2 rolls + edamame',
      description: 'Combo noche jue–sáb.',
      discountPercent: 10,
      daysActive: ['thursday', 'friday', 'saturday'],
    },
  ],
  inventory: [
    {
      name: 'Salmón fresco (kg)',
      unit: 'kg',
      quantity: 4.5,
      lowStockThreshold: 3,
      linkedDishNames: ['Philadelphia roll', 'Sashimi mix 12 pzas'],
    },
    {
      name: 'Atún (kg)',
      unit: 'kg',
      quantity: 2.2,
      lowStockThreshold: 1.5,
      linkedDishNames: ['Spicy tuna', 'Sashimi mix 12 pzas'],
    },
    {
      name: 'Arroz sushi (kg)',
      unit: 'kg',
      quantity: 25,
      lowStockThreshold: 10,
      linkedDishNames: ['Philadelphia roll', 'Nigiri combo'],
    },
    {
      name: 'Palta (u)',
      unit: 'u',
      quantity: 8,
      lowStockThreshold: 12,
      linkedDishNames: ['Philadelphia roll', 'California roll'],
    },
    {
      name: 'Queso crema (kg)',
      unit: 'kg',
      quantity: 3,
      lowStockThreshold: 1.5,
      linkedDishNames: ['Philadelphia roll'],
    },
  ],
  tableLayout: {
    areas: [
      { name: 'Salón', tables: [2, 2, 2, 4, 4, 4, 6] },
      { name: 'Barra', tables: [1, 1, 1, 1] },
    ],
  },
  media: {
    logo: photo('logo.png'),
    cover: photo('hero.jpg'),
    hero: photo('hero.jpg'),
    interior: [photo('interior.jpg'), photo('hero.jpg')],
  },
  historyDays: 72,
};
