import type { TaskCapability } from '../types/planner.types';

/** Metadatos declarativos por tarea — el Planner compone planes desde aquí, no desde flujos hardcodeados */
export const TASK_CAPABILITIES: Record<string, TaskCapability> = {
  'leads.discover_restaurants': {
    taskKey: 'leads.discover_restaurants',
    label: 'Búsqueda web',
    category: 'ai',
    dependsOnTaskKeys: [],
    estimatedCostUsd: 0.012,
    estimatedDurationMs: 8000,
    requiresApproval: false,
    cacheTtlSeconds: 86400,
    preferredModels: ['gemini-2.5-flash', 'gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.enrich_candidate': {
    taskKey: 'leads.enrich_candidate',
    label: 'Enriquecer candidato',
    category: 'code',
    dependsOnTaskKeys: ['leads.discover_restaurants'],
    estimatedCostUsd: 0,
    estimatedDurationMs: 50,
    requiresApproval: false,
    preferredModels: [],
    budgetModels: [],
  },
  'leads.analyze_digital_presence': {
    taskKey: 'leads.analyze_digital_presence',
    label: 'Análisis digital',
    category: 'code',
    dependsOnTaskKeys: [],
    estimatedCostUsd: 0,
    estimatedDurationMs: 30,
    requiresApproval: false,
    preferredModels: [],
    budgetModels: [],
  },
  'leads.detect_problems': {
    taskKey: 'leads.detect_problems',
    label: 'Detectar problemas',
    category: 'code',
    dependsOnTaskKeys: ['leads.analyze_digital_presence'],
    estimatedCostUsd: 0,
    estimatedDurationMs: 20,
    requiresApproval: false,
    preferredModels: [],
    budgetModels: [],
  },
  'leads.business_diagnosis': {
    taskKey: 'leads.business_diagnosis',
    label: 'Diagnóstico comercial',
    category: 'ai',
    dependsOnTaskKeys: ['leads.analyze_digital_presence'],
    estimatedCostUsd: 0.002,
    estimatedDurationMs: 2500,
    requiresApproval: false,
    cacheTtlSeconds: 604800,
    preferredModels: ['gemini-2.5-flash-lite', 'gemini-2.5-flash'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.calculate_score': {
    taskKey: 'leads.calculate_score',
    label: 'Calcular score',
    category: 'code',
    dependsOnTaskKeys: [],
    estimatedCostUsd: 0,
    estimatedDurationMs: 10,
    requiresApproval: false,
    preferredModels: [],
    budgetModels: [],
  },
  'leads.generate_demo': {
    taskKey: 'leads.generate_demo',
    label: 'Generar demo',
    category: 'ai',
    dependsOnTaskKeys: ['leads.business_diagnosis'],
    estimatedCostUsd: 0.0015,
    estimatedDurationMs: 2000,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.draft_message_whatsapp': {
    taskKey: 'leads.draft_message_whatsapp',
    label: 'Mensaje WhatsApp',
    category: 'ai',
    dependsOnTaskKeys: ['leads.calculate_score'],
    estimatedCostUsd: 0.001,
    estimatedDurationMs: 1800,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.draft_message_instagram': {
    taskKey: 'leads.draft_message_instagram',
    label: 'Mensaje Instagram',
    category: 'ai',
    dependsOnTaskKeys: ['leads.calculate_score'],
    estimatedCostUsd: 0.001,
    estimatedDurationMs: 1800,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.draft_message_email': {
    taskKey: 'leads.draft_message_email',
    label: 'Email comercial',
    category: 'ai',
    dependsOnTaskKeys: ['leads.calculate_score'],
    estimatedCostUsd: 0.0012,
    estimatedDurationMs: 2200,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.draft_followup': {
    taskKey: 'leads.draft_followup',
    label: 'Seguimiento',
    category: 'ai',
    dependsOnTaskKeys: ['leads.draft_message_whatsapp'],
    estimatedCostUsd: 0.0008,
    estimatedDurationMs: 1500,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.suggest_next_action': {
    taskKey: 'leads.suggest_next_action',
    label: 'Próxima acción',
    category: 'ai',
    dependsOnTaskKeys: [],
    estimatedCostUsd: 0.0005,
    estimatedDurationMs: 1200,
    requiresApproval: false,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.generate_proposal': {
    taskKey: 'leads.generate_proposal',
    label: 'Propuesta comercial',
    category: 'ai',
    dependsOnTaskKeys: ['leads.business_diagnosis'],
    estimatedCostUsd: 0.002,
    estimatedDurationMs: 2500,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.generate_prospect_bundle': {
    taskKey: 'leads.generate_prospect_bundle',
    label: 'Generar paquete prospecto completo',
    category: 'ai',
    dependsOnTaskKeys: [],
    estimatedCostUsd: 0.012,
    estimatedDurationMs: 90_000,
    requiresApproval: false,
    preferredModels: ['gemini-2.5-flash'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.run_prospect_pipeline': {
    taskKey: 'leads.run_prospect_pipeline',
    label: 'Pipeline prospecto completo (12 etapas)',
    category: 'ai',
    dependsOnTaskKeys: ['leads.business_diagnosis'],
    estimatedCostUsd: 0.045,
    estimatedDurationMs: 180_000,
    requiresApproval: true,
    preferredModels: ['gemini-2.5-flash'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
  'leads.analyze_client_reply': {
    taskKey: 'leads.analyze_client_reply',
    label: 'Analizar respuesta',
    category: 'ai',
    dependsOnTaskKeys: [],
    estimatedCostUsd: 0.0006,
    estimatedDurationMs: 1200,
    requiresApproval: false,
    preferredModels: ['gemini-2.5-flash-lite'],
    budgetModels: ['gemini-2.5-flash-lite'],
  },
};

export function getTaskCapability(taskKey: string): TaskCapability {
  return (
    TASK_CAPABILITIES[taskKey] ?? {
      taskKey,
      label: taskKey,
      category: 'ai',
      dependsOnTaskKeys: [],
      estimatedCostUsd: 0.001,
      estimatedDurationMs: 2000,
      requiresApproval: false,
      preferredModels: ['gemini-2.5-flash-lite'],
      budgetModels: ['gemini-2.5-flash-lite'],
    }
  );
}
